### ISSUE TITLE
Last line missing from output when it doesn't have an endline

### ISSUE THREAD

**Issue by lervag** [gpanders/vim-medieval#11] opened 2022-05-08 20:04 UTC
Given this code block:

``````
<!-- target: out -->
```sh
curl -s https://jsonplaceholder.typicode.com/todos/1
```
``````

I get the following output from doing `:EvalBlock`:

```````
<!-- name: out -->
```json
{
  "userId": 1,
  "id": 1,
  "title": "delectus aut autem",
  "completed": false
```
```````

I believe the problem is related to the fact that the curl output does not have a final endline?

(By the way, thanks for this plugin. I find it quite convenient for e.g. simple testing of shell commands and curl calls!)

**Comment by gpanders** [comment] 2022-05-08 20:27
Thanks for the issue report. This should be fixed by #12. Would you mind testing it out and confirming that the issue is resolved?

**Comment by lervag** [comment] 2022-05-08 20:35
Thanks, that was quick! I confirm #12 fixes my issue!

**Closed** 2022-05-08 20:38 UTC

**Comment by lervag** [comment] 2022-05-08 20:49
Thanks again!
